### ISSUE TITLE
Can't start the project

### ISSUE THREAD

**Issue by miguelrincon** [gejun2008/employee-list#1]
```
$ npm start

> angular-quickstart@1.0.0 start /home/mr155795/work/git/employee-list
> tsc && concurrently "tsc -w" "lite-server" 

node_modules/@types/jasmine/index.d.ts(40,52): error TS1005: '=' expected.
node_modules/@types/jasmine/index.d.ts(42,62): error TS1005: '=' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 

```

**Comment by gejun2008** [comment]
sorry,  The reson is @types/jasmine version not be compatible with typescript. so we need modify package.json downgrade @types/jasmine .

"devDependencies": {
    "concurrently": "^3.1.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.0.10",

    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~4.0.13",
    "rimraf": "^2.5.4",

    "@types/node": "^6.0.46",
    # "@types/jasmine": "2.5.36",
    "@types/selenium-webdriver": "^2.53.33"
  },

then we should reinstall @types/jasmine, after install the package, use "npm start".
